### ISSUE TITLE
Edit crew function in DRB

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#177]
During crew change, Typically Wednesdays, the managers are modifying crews on the crew management page. When there is a haul assignment with this crew it gets "stuck" and logistics can no longer update the status of the crew.
On the Crew Mgmt page, there is a linkage to the assignments and when a crew is updated the assignment was designed to move with the crew (this follows the design of the pumper page). The status on the bulker job board are independent of this. 
In order to get alignment, we will break the linkage between the crew modification and the assignments. This will allow the managers to continue to modify crews as they currently do and not affect the crews and their assigned hauls on the job board. 

The emails received (a few every week that requires database level fixes) are similar to the following:
"Can I please get Bruce and Stefan cycled through under Lloydminster on the bulker assignment job board. Yesterday management was adjusting crew while they had a load in and I believe this caused the glitch."

**Comment by awangatsanjel** [comment]
@JasonSchneider19 
There are two directions change.

1. Editing crew in "Crew Mgmt" changes old crew's assignment, this applies to both bulker and pumper crews.
2. Changing crew in "Job Board"-->"Pumper Assignment" moves old crew planned schedule to new crew.

Both of these cross-board operations are not conceptually correct. The first one affected product haul,  it can be fixed. 

The second one needs to be fixed too. The requirement needs to be updated.

**Comment by JasonSchneider19** [comment]
@awangatsanjel 
On the Crew Mgmt page - Pumper Schedule and Bulker Schedule

Cut the relation between editing crew and moving plan schedules

•	We can edit a crew - add/change crew members & units
•	It will create a “new” crew on the board
•	The new crew will not have any planned days
•	The planned days remain with the original crew
•	The new crew will need to have their schedules planned

For example:
we have the following crew that is planned:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/dad028ba-ca91-4e8d-aecf-c2ec312e0b37)
We will add another member to the crew
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/d28afe5e-8c7c-48de-aa0b-b93971eeb9b1)
it currently does the following:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/f41e6ebd-263e-4a81-8e5e-df7563f29eac)

we would like it to do the following:
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/97102165-b624-4b45-99a1-0a8af110f541)

The current planned crew is left in place, and the new crew is added to the board, but not planned
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/e4226e54-f99a-4933-adf7-4b5dcdc909bc)

**Comment by awangatsanjel** [comment]
Suggestion.

1.	Clarify “Edit Crew” function is “Copy and create new crew” function to provide the convenience of building new crew.
2.	Delete and Deactivate functions are convenient enough to correct the mistake if building new crew from scratch.
3.	All planning or replanning should be down with existing DRB functions. Since the calendar is pumper/bulker centered, so the crews are grouped. It is easy to move the plan schedule among different groups with a good visual view. 

We only need to cut off the relation between editing crew and moving plan schedules.

Jason's response
Ok, so I just called Shawn to ask him about this.
I believe that we are all on the same page now…
Cut the relation between editing crew and moving plan schedules
-	We can edit a crew
-	It will create a “new” crew on the board
-	The new crew will not have any planned days
-	The planned days remain with the original crew
-	The new crew will need to have their schedules planned
This should allow easy addition of crews
Should prevent the moving of planned crews and messing with the job board.
