### ISSUE TITLE
Offload all selection on product haul

### ISSUE THREAD

**Issue by JasonSchneider19** [Sanjel-Energy-Services/eService_WorkItems#183]
When creating a product haul, we are selecting the bin to offload into.
We need to type in the tonnage to be offloaded. More often than not, we put the whole load into a single bin.
In order to make things simpler and to remove the chance of a typing error, add an "Offload All" checkbox.
If selected, if will all the total "Haul Amount" to the selected bin.
If not selected, the blend can be divided into the bins as desired.
![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/0185077c-8abf-4082-9ca8-2c5d580151c5)

**Comment by wistaria623** [comment]
Relevant use case:
Haul blend from BulkPlant Bin
Schedule Product Hal from Rig Board Bin 
Schedule Product Hal from Rig Board Blend
Haul blend from Rig Board Blend

1. Add a check box control behind the RigBin input box.
2. The default value is deselected.
3. If selected, if will all the total "Haul Amount" to the selected bin.
     - UnSelected,offload amount =0
5. If not selected, the blend can be divided into the bins as desired.
UI Mock


![image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/95711838/0185077c-8abf-4082-9ca8-2c5d580151c5)

**Comment by tobeytong** [comment]
每个Bin后面增加一个checkbox
当勾选checkbox的时候，将HaulAmout的值填写到对应的Bin的TextBox中
（如果上面值出现负值，则还是填写0）
填写后，所有的Bin的TextBox变成只读的

如果切换checkox，那么值跟着切换，但是只读属性不变

只有取消掉checkbox后，所有的Bin的textbox才变成可写的

一次只能勾选一个checkbox

**Comment by tobeytong** [comment]
@awangatsanjel  @wistaria623 

现在有个问题，在RigBord的Bin列创建ProductHaul的时候，
是否需要Offload all的功能

因为这个页面，在Amout填写数字后，会自动填写到对应的Bin的文本框中，加这个是否多余

**Comment by wistaria623** [comment]
@JasonSchneider19 

step:
1. schedule product haul from rig board blend
2. input ：Amount =10
3. selected offload all  for bin2080 :Bin 2080 offload amount =10
4. update Amount =15

Which of the following is the expected outcome?
- Bin 2080 offload Amount =10  
- Bin 2080 offload Amount =15
- Bin 2080 offload Amount =0, Offload all is unselected

![Image](https://github.com/Sanjel-Energy-Services/eService_WorkItems/assets/37645176/1d216303-038e-4cbb-9001-19bbe885b0f1)

**Comment by JasonSchneider19** [comment]
@wistaria623 
step:
schedule product haul from rig board blend
input ：Amount =10
selected offload all for bin2080 :Bin 2080 offload amount should update to "Amount" value (15)
update Amount =15

The following would be expected:
Bin 2080 offload Amount =15

**Comment by tobeytong** [comment]
当我们在RigBoard的Bin上创建Product的时候，填写的Amout值会自动填写到对应的Bin中，当我们选择了offload checkbox后，Amout值会变到选中的Bin中去，当我们修改Amout值后，值会回到对应的对应的Bin中，同时，所有的offload checkbox会处于没有选择的状态

**Comment by awangatsanjel** [comment]
@wistaria623 @tobeytong 
你们对需求理解的有一点乱。没有理解Haull All 或是 OffLoad All的本质。实质上它只是一个快捷方式来设置一些默认值，并没有改变原有的基本逻辑。
Jason的需求示例是Haul Blend from Bulk Plant Bin，也就是可能出现两个以上Bin的情况，可以通过Offload All去自动添写，从而避免输入数字时的人为错误。
`In order to make things simpler and to remove the chance of a typing error, add an "Offload All" checkbox.`

你们检查其他场景，这很好，但是没有把逻辑理顺清楚

1. 如果一个Bin的OffLoad All被勾选，那么在Amount值变动时，相应的Bin的值也要自动同步。

比如： Schedule Product Haul on Rig Bin中，原来的点击的Bin自动同步的机制，在加了Offload All checkbox以后，可以理解为OffLoad All被自动勾选。其他的Bin是disable的，不能填写

2. 如果没有OffLoad All 被勾选，所有的Bin都是可以填写的，OffLoad总量与Load Amount的Validation要给出Alert.
3. 如果所有的Bin中都没有填写Offload Amount, 所有OffLoad checkbox都是enabled。
4. 如果任何一个多个Bin中填写了Offload Amount, 所有OffLoad checkbox都是disabled。即便有只有一个Bin填写的数字与OffLoad总量一致，不要自动去勾选OffLoad All。这样保持所有逻辑一致

OffLoad All只相当于一个帮助添写的快捷键，只在当前页面中工作，并不需要保存。
那么当Reschedule时，只要按上面的逻辑把数据加载回来即可。如果Schedule的时候是点OffLoad All填写的OffLoad Amount，Reschedule时，所有的checkbox都是disabled。

**Comment by wanghuan69** [comment]
开发分支验证通过
